### ISSUE TITLE
New User - Welcome Email

### ISSUE THREAD

**Issue by bill-curran** [leegarner-glfusion/profile#9]
My customer has asked if we can create 2 emails - one at user creation time that shows the user all of the data he enters for verification. He would also like an email when a user makes a change to his custom data.  Their users are all old people (pensioners) and they have to be handheld though a lot of the processes.

They are willing to pay if that will help!

Bill

**Comment by leegarner** [comment]
I think that would be simple enough. Offhand they might get 2 emails at
registration, one from the stock glFusion system and one from the Custom
Profile (since the stock notification doesn't include the info). If you
would only need all the data listed when updated, that would be even easier.
